# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  # Forward a port from the guest to the host, which allows for outside
  # computers to access the VM, whereas host only networking does not.
  #config.vm.forward_port 80, 8080
  #config.vm.forward_port 443, 8443
  #config.vm.forward_port 8000, 8000

    # Ubuntu
    config.vm.define :lucid do |lucid_config|
        config.vm.box = "lucid32"
        config.vm.box_url = "http://files.vagrantup.com/lucid32.box"
        config.vm.provision :shell, :path => "vagrant-debian-like-provision.sh"
        config.vm.base_mac = '0E1000001004'
    end

    config.vm.define :precise do |precise_config|
        config.vm.box = "precise"
        config.vm.box_url = "http://files.vagrantup.com/precise32.box"
        config.vm.provision :shell, :path => "vagrant-debian-like-provision.sh"
        config.vm.base_mac = '0E1000001204'
    end

    config.vm.define :quantal do |quantal_config|
        config.vm.box = "quantal"
        config.vm.box_url = "http://static.aldoborrero.com/vagrant/quantal64.box"
        config.vm.provision :shell, :path => "vagrant-debian-like-provision.sh"
        config.vm.base_mac = '0E1000001210'
    end

    # Debian
    config.vm.define :squeeze do |squeeze_config|
        config.vm.box = "squeeze"
        config.vm.box_url = "https://dl.dropbox.com/u/2289657/squeeze32-vanilla.box"
        config.vm.provision :shell, :path => "vagrant-debian-like-provision.sh"
        config.vm.base_mac = '0E2000000006'
    end

    config.vm.define :wheezy do |wheezy_config|
        config.vm.box = "wheezy"
        config.vm.box_url = "https://github.com/downloads/leapcode/minimal-debian-vagrant/wheezy.box"
        config.vm.provision :shell, :path => "vagrant-debian-like-provision.sh"
        config.vm.base_mac = '0E2000000007'
    end

end
